name: REST Unit_Tests 😎 

on:
  pull_request:
    branches:
      - 'rest/**'
      - 'master'
      - 'staging-rest-**'

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      - name: Checkout EmptyProject
        uses: actions/checkout@v2
        with:
         repository: mobiledgex/edge-cloud-sdk-unity
         ref: 'empty-project'
         token: ${{ secrets.GITHUB_TOKEN }}
         path: ./project
         lfs: true

      - name: Checkout SDK branch into EmptyProject
        uses: actions/checkout@v2
        with:
         path: ./project/EmptyProject/Assets
         lfs: true

      # Editor tests not needed (Package is not imported)
      - name: Remove Editor tests 
        run: |
          rm -rf ./project/EmptyProject/Assets/Tests/Editor
          rm ./project/EmptyProject/Assets/Tests/Editor.meta

      - name: Run Tests using Unity TestRunner
        uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: project/EmptyProject
          testMode: EditMode
          artifactsPath: EditorMode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName:  Editor Test Results

      # Upload Test results and logs         
      - name: Upload tests' results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for EditorMode
          path: ${{ steps.tests.outputs.artifactsPath }}